/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/evals/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evals Summary */
        get: operations["evals_summary_evals_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/run/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evals Run */
        get: operations["evals_run_evals_run__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Stream */
        post: operations["ask_stream_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Stream */
        post: operations["agent_stream_agent_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Deepagent */
        post: operations["ask_deepagent_ask_agent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask/agent/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Deepagent Endpoint */
        post: operations["resume_deepagent_endpoint_ask_agent_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask/agent/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Deepagent Run */
        post: operations["start_deepagent_run_ask_agent_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask/agent/run/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deepagent Run Events */
        get: operations["deepagent_run_events_ask_agent_run__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_source__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Qa Memories */
        get: operations["qa_memories_qa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qa/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Qa Memory */
        get: operations["qa_memory_qa__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentRequest */
        AgentRequest: {
            /** Question */
            question: string;
        };
        /** AgentRunStarted */
        AgentRunStarted: {
            /** Run Id */
            run_id: string;
        };
        /** AnswerEvent */
        AnswerEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "answer";
            /** Text */
            text: string;
            /** Thread Id */
            thread_id: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /**
             * Format
             * @description Answer format; only affects the openai-compat path.
             * @default prose
             * @enum {string}
             */
            format: "prose" | "claims";
            /**
             * Model
             * @description Generation model picker, resolved to an OpenRouter id via GEN_MODELS.
             * @default pro
             * @enum {string}
             */
            model: "pro" | "flash";
            /**
             * Method
             * @description Retriever funnel; production default is rerank.
             * @default rerank
             * @enum {string}
             */
            method: "vector" | "hybrid" | "rerank";
            /**
             * Query Enhancement
             * @description Query rewriting: HyDE hypothetical or multi-query paraphrase fusion.
             */
            query_enhancement?: ("hyde" | "multi_query") | null;
            /**
             * Parent Document
             * @description Widen each hit to its neighbouring chunks before answering.
             * @default false
             */
            parent_document: boolean;
            /**
             * Hype
             * @description Match against index-time hypothetical questions instead of raw chunks.
             * @default false
             */
            hype: boolean;
            /**
             * Top K
             * @description Chunks handed to the generator (the citable pool); can't exceed RERANK_DEPTH, since rerank only has that many candidates to keep.
             * @default 25
             */
            top_k: number;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Sources */
            sources: components["schemas"]["Source"][];
        };
        /** AwaitingApproval */
        AwaitingApproval: {
            /**
             * Status
             * @default awaiting_approval
             * @constant
             */
            status: "awaiting_approval";
            /** Thread Id */
            thread_id: string;
            /** Pending */
            pending: {
                [key: string]: string;
            }[];
        };
        /**
         * AwaitingApprovalEvent
         * @description The HITL gate paused the run; POST /ask/agent/resume continues it.
         */
        AwaitingApprovalEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "awaiting_approval";
            /** Thread Id */
            thread_id: string;
            /** Pending */
            pending: {
                [key: string]: string;
            }[];
        };
        /** Citation */
        Citation: {
            /** Claim */
            claim: string;
            /** Cited Text */
            cited_text: string;
            /** Chunk Id */
            chunk_id: number;
            /** Title */
            title: string;
            /** Source */
            source: string;
        };
        /**
         * CitationEvent
         * @description One source backing the answer, sent once the text is complete.
         */
        CitationEvent: {
            /** Claim */
            claim: string;
            /** Cited Text */
            cited_text: string;
            /** Chunk Id */
            chunk_id: number;
            /** Title */
            title: string;
            /** Source */
            source: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "citation";
        };
        /**
         * CorpusSource
         * @description A corpus passage the deep agent's answer cites. `n` is its stable [n] marker in
         *     the answer text; chunk_id opens it via GET /source/{chunk_id}.
         */
        CorpusSource: {
            /** N */
            n: number;
            /** Chunk Id */
            chunk_id: number;
            /** Title */
            title: string;
            /** Source */
            source: string;
        };
        /**
         * DeepAgentEvent
         * @description One SSE frame from GET /ask/agent/run/{run_id}: a `status` per tool call and a
         *     `result` per tool result as the agent works, then `sources` + a terminal `answer`
         *     — or `awaiting_approval`, or `error`.
         */
        DeepAgentEvent: components["schemas"]["StatusEvent"] | components["schemas"]["ResultEvent"] | components["schemas"]["SourcesEvent"] | components["schemas"]["AnswerEvent"] | components["schemas"]["AwaitingApprovalEvent"] | components["schemas"]["ErrorEvent"];
        /** DeepAgentRequest */
        DeepAgentRequest: {
            /** Question */
            question: string;
            /** Thread Id */
            thread_id: string;
            /** Research Budget */
            research_budget?: number | null;
        };
        /** DeepAgentResponse */
        DeepAgentResponse: {
            /** Answer */
            answer: string;
            /** Thread Id */
            thread_id: string;
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** Message */
            message: string;
        };
        /** EvalsSummary */
        EvalsSummary: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
            final: components["schemas"]["FinalConfig"] | null;
        };
        /** FinalConfig */
        FinalConfig: {
            /** Config Name */
            config_name: string | null;
            /** Config Hash */
            config_hash: string | null;
            dev: components["schemas"]["SplitSummary"] | null;
            test: components["schemas"]["SplitSummary"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** QAMemory */
        QAMemory: {
            /** Key */
            key: string;
            /** Question */
            question: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QAMemoryDetail */
        QAMemoryDetail: {
            /** Key */
            key: string;
            /** Question */
            question: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Answer */
            answer: string;
            /** Corpus Sources */
            corpus_sources: components["schemas"]["CorpusSource"][];
            /** Web Urls */
            web_urls: string[];
            /** Research Files */
            research_files: {
                [key: string]: string;
            };
        };
        /**
         * ResultEvent
         * @description What a tool returned, correlated to its StatusEvent by call_id.
         */
        ResultEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "result";
            /** Call Id */
            call_id: string;
            /** Preview */
            preview: string;
        };
        /** ResultRow */
        ResultRow: {
            /** Question Id */
            question_id: number;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Split */
            split: string | null;
            /** Scores */
            scores: {
                [key: string]: boolean;
            };
            /** Rationales */
            rationales: {
                [key: string]: string;
            };
        };
        /** ResumeRequest */
        ResumeRequest: {
            /** Thread Id */
            thread_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
        };
        /** RunDetail */
        RunDetail: {
            /** Run Id */
            run_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Git Sha */
            git_sha: string;
            /** Config Name */
            config_name: string | null;
            /** Config Hash */
            config_hash: string | null;
            /** Results */
            results: components["schemas"]["ResultRow"][];
        };
        /** RunSummary */
        RunSummary: {
            /** Run Id */
            run_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Git Sha */
            git_sha: string;
            /** Config Name */
            config_name: string | null;
            /** Config Hash */
            config_hash: string | null;
            /** N */
            n: number;
            /** Pass Rate */
            pass_rate: {
                [key: string]: number;
            };
            /** Cost */
            cost: number;
            /** Latency Ms */
            latency_ms: number;
        };
        /** Source */
        Source: {
            /** Title */
            title: string;
            /** Source */
            source: string;
            /** Distance */
            distance: number | null;
        };
        /** SourcePassage */
        SourcePassage: {
            /** Title */
            title: string;
            /** Section */
            section: string;
            /** Chunk Index */
            chunk_index: number;
            /** N Chunks */
            n_chunks: number;
            /** Before */
            before: string;
            /** Chunk */
            chunk: string;
            /** After */
            after: string;
        };
        /** SourcesEvent */
        SourcesEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sources";
            /** Sources */
            sources: components["schemas"]["CorpusSource"][];
        };
        /** SplitSummary */
        SplitSummary: {
            /** Run Id */
            run_id: number;
            /** N */
            n: number;
            /** Pass Rate */
            pass_rate: {
                [key: string]: number;
            };
        };
        /**
         * StatusEvent
         * @description A tool call the agent started. scope "research" = inside the web-research subagent.
         */
        StatusEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "status";
            /**
             * Scope
             * @enum {string}
             */
            scope: "main" | "research";
            /** Call Id */
            call_id: string;
            /** Tool */
            tool: string;
            /** Label */
            label: string;
        };
        /**
         * StreamEvent
         * @description One SSE frame from POST /ask/stream: `text` events, then one `citation` per source.
         */
        StreamEvent: components["schemas"]["TextEvent"] | components["schemas"]["CitationEvent"];
        /**
         * TextEvent
         * @description A slice of the answer, as it generates.
         */
        TextEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AgentRequest = components['schemas']['AgentRequest'];
export type AgentRunStarted = components['schemas']['AgentRunStarted'];
export type AnswerEvent = components['schemas']['AnswerEvent'];
export type AskRequest = components['schemas']['AskRequest'];
export type AskResponse = components['schemas']['AskResponse'];
export type AwaitingApproval = components['schemas']['AwaitingApproval'];
export type AwaitingApprovalEvent = components['schemas']['AwaitingApprovalEvent'];
export type Citation = components['schemas']['Citation'];
export type CitationEvent = components['schemas']['CitationEvent'];
export type CorpusSource = components['schemas']['CorpusSource'];
export type DeepAgentEvent = components['schemas']['DeepAgentEvent'];
export type DeepAgentRequest = components['schemas']['DeepAgentRequest'];
export type DeepAgentResponse = components['schemas']['DeepAgentResponse'];
export type ErrorEvent = components['schemas']['ErrorEvent'];
export type EvalsSummary = components['schemas']['EvalsSummary'];
export type FinalConfig = components['schemas']['FinalConfig'];
export type HTTPValidationError = components['schemas']['HTTPValidationError'];
export type QAMemory = components['schemas']['QAMemory'];
export type QAMemoryDetail = components['schemas']['QAMemoryDetail'];
export type ResultEvent = components['schemas']['ResultEvent'];
export type ResultRow = components['schemas']['ResultRow'];
export type ResumeRequest = components['schemas']['ResumeRequest'];
export type RunDetail = components['schemas']['RunDetail'];
export type RunSummary = components['schemas']['RunSummary'];
export type Source = components['schemas']['Source'];
export type SourcePassage = components['schemas']['SourcePassage'];
export type SourcesEvent = components['schemas']['SourcesEvent'];
export type SplitSummary = components['schemas']['SplitSummary'];
export type StatusEvent = components['schemas']['StatusEvent'];
export type StreamEvent = components['schemas']['StreamEvent'];
export type TextEvent = components['schemas']['TextEvent'];
export type ValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    evals_summary_evals_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalsSummary"];
                };
            };
        };
    };
    evals_run_evals_run__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_stream_agent_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_deepagent_ask_agent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeepAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepAgentResponse"] | components["schemas"]["AwaitingApproval"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_deepagent_endpoint_ask_agent_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepAgentResponse"] | components["schemas"]["AwaitingApproval"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_deepagent_run_ask_agent_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeepAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deepagent_run_events_ask_agent_run__run_id__get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepAgentEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_source__chunk_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePassage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    qa_memories_qa_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QAMemory"][];
                };
            };
        };
    };
    qa_memory_qa__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QAMemoryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
